version: '2'
services:
  app:
    build: .
    command: nodemon server.js
    ports:
    - 8000:8000
    volumes:
    - /src/node_modules
    - .:/src
    environment:
      NODE_ENV: development
      SITE_URL: http://localhost:8000
      SERVER_URL: http://localhost:3000
      API_PREFIX: /api/v1
