version: 2
jobs:
  build:
    docker:
      - image: node:8

    working_directory: ~/repo

    environment:
      - STAGING_BRANCH: develop

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install --unsafe-perm

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Building site
          command: |
            if [ "${CIRCLE_BRANCH}" == "${STAGING_BRANCH}" ]; then
              ./node_modules/.bin/grunt build
            else
              echo "Skip building site"
            fi
      - run:
          name: Deploy staging to Surge
          command: |
            if [ "${CIRCLE_BRANCH}" == "${STAGING_BRANCH}" ]; then
              cp ./public/views/layouts/default.html ./public/index.html
              ./node_modules/surge/lib/cli.js --project ./public --domain mapascoletivos.surge.sh
            else
              echo "Not the branch you're looking for, skipping deploy"
            fi